### ISSUE TITLE
Interpolation error

### ISSUE THREAD

**Issue by xinyu1905** [QuantumMaterialsModelling/vasp-phonopy-sscha#1]
Thank you very much for sharing this code! 
I'm having some problems interpolating the force constants. The produced POSCAR_X is unreasonable  when X is an odd number，like this
POSCAR_1

> generated by phonopy
> 1.0
>      20.51030558015857        0.0        0.0947411230257034
>      0.0        20.860917147463063        0.0
>      -3.6106018498087886        0.0        20.858517349609922
> Zr O
> 256   512
> Cartesian
>  -438553.80855691695  -543280.1570566504  286518.73247570207
>  -438553.671591944  -543279.3267175994  286519.99236833915
>  -438552.4253739102  -543280.9669509121  286518.48628210207
>  -438553.2039323958  -543279.7152609768  286519.35185900383
>  22257.10144415168  -650241.3606646878  -26906.01525612041
>  22257.04413241384  -650243.0055896948  -26905.800726940302
>  22258.04251456885  -650241.36534403  -26906.07351934072
>  22256.97276405285  -650243.326194487  -26905.606374732888
>  676737.4450210299  440318.2365866  -1065226.153565556
>  676737.3888753173  440316.44367526815  -1065225.6138304048
>  676738.2783565173  440317.05514217593  -1065223.672337983
>  676736.9845212774  440315.60200564977  -1065223.2785678827
>  463511.2382516823  -178955.23868022897  178243.2662837978
>  463508.8697193315  -178954.8631244169  178242.75283586068
>  463509.571465863  -178956.17992234929  178243.95688892683
>  463510.1420496272  -178955.4577892833  178244.10510047583
>  -512571.4562084836  129374.96537315416  236796.2457425185
>  -512572.00775864033  129374.2109303694  236797.78541015953
>  -512571.6212766557  129374.57575351062  236798.62183244704
>  -512572.5869720848  129373.62711372132  236798.6442055317
>  -465624.63828789274  -712231.6612378139  244633.56677149824
>  -465624.71355332155  -712233.0207340133  244633.36209637148

> 
……

but when X is an even number, the POSCAR_X is right,

> POSCAR_2
> generated by phonopy
> 1.0
>      20.51030558015857        0.0        0.0947411230257034
>      0.0        20.860917147463063        0.0
>      -3.6106018498087886        0.0        20.858517349609922
> Zr O
> 256   512
> Cartesian
>  -1.156085030623753  1.2059708210784816  -7.136410832497273
>  -1.2930499937341968  -0.4527329647789134  -7.396301335088294
>  -1.6483928367120877  1.0158628682616653  -6.727812692393802
>  -0.8698343390390317  -1.0641916639286808  -6.593387325684155
>  -8.901504694026082  8.487363815361661  7.135005608180705
>  -8.844192946183545  9.303924087477272  7.920478562602579
>  -8.951699910312808  7.492040942939613  7.355673368657643
>  -7.881949382315635  8.624526803169537  7.888531029361075
>  6.68065870188174  -4.944169545858398  1.8320228887938088
>  6.736804424631131  -3.979622948912812  2.2922898723478973
>  3.1275965655618143  -4.762727336411295  20.37171720594545
>  4.421431817404636  -4.137955406993245  20.97794937418953
>  -1.3266005210294092  -8.655342305462185  11.779341912553198
>  1.0419318397890929  -9.859262852396236  13.292791984228195
>  1.2310604993349252  -8.714102399657484  11.251141323743738
>  0.6604767469804003  -10.264600062506204  12.102932043238864
>  1.5849811954089108  -4.073497610752852  3.623770345081109
>  2.1365313621836144  -4.147419560857952  3.084104838637768
>  2.6409245684790688  -4.683880181715743  1.4100849567052507
>  3.606620009446236  -4.563604989305652  2.3877141405938107
> ……
how can i fix it?

**Comment by luigiranalli96** [comment]
Sorry for the delay in the response. I was busy but I am planning to update a full tutorial in order to make things easier for the user. It is a strange issue, honestly I have never obtained something like this also on other materials. 
A question: in the "data" folder you should have obtained the scf_population1_num.dat ensembles elaborated by sscha. Do you have the same problem there?

Luigi

**Comment by xinyu1905** [comment]
Thanks for your response, I'm looking forward to the detailed tutorial. 
in the "data" folder, I have not obtained the scf_population1_num.dat file, but the u_population1_XX.dat file.

**Comment by luigiranalli96** [comment]
The scf_ files are stored in data/position/

Luigi

————————————————————

Luigi Ranalli (MSc, Doctoral Student)

Computational Materials Physics
Faculty of Physics
University of Vienna
Kolingasse 14-16, Room 3.07, 1090 Vienna
***@***.***
Tel: +393206867752 (Italy)
Tel: +4368110359269 (Austria)
Il 23 nov 2022, 03:23 +0100, xinyu1905 ***@***.***>, ha scritto:

**Comment by xinyu1905** [comment]
i found it, the scf_population1_num.dat is  consistent with file POSCAR_1

**Comment by luigiranalli96** [comment]
You are welcome! :)

Can you send me a reproducible example? For examole the dynamical matrixes, and how you called vaspsscha?

Luigi

————————————————————

Luigi Ranalli (MSc, Doctoral Student)

Computational Materials Physics
Faculty of Physics
University of Vienna
Kolingasse 14-16, Room 3.07, 1090 Vienna
***@***.***
Tel: +393206867752 (Italy)
Tel: +4368110359269 (Austria)
Il 23 nov 2022, 03:47 +0100, xinyu1905 ***@***.***>, ha scritto:

**Comment by xinyu1905** [comment]
I download  the vasp-phonopy-sscha code and called vaspsscha in the subfolder vasp-phonopy-sscha by executing the command

python interface.py 

I have copied "FORCE_CONSTANTS, POSCAR, qpoints.yaml" into this folder before running the command.

In addition, I modified the code to read 1.txt in interface.py,
def write_dyn(self):
        import linecache
        # !!! read rec latt vectors
        #aa=pd.read_csv("1.txt", engine='python', sep="   | |,", skiprows=3, nrows=3, header=None)
        a1=np.array(linecache.getline("1.txt",4).replace(',','').split()[2:5],dtype=np.float64)
        a2=np.array(linecache.getline("1.txt",5).replace(',','').split()[2:5],dtype=np.float64)
        a3=np.array(linecache.getline("1.txt",6).replace(',','').split()[2:5],dtype=np.float64)
        # b1,b2,b3 in units of 2pi/a (read in 1/A, so multiply by alat in A)
        b1=a1*self.supercell_multiplier/angstrom_to_bohr
        b2=a2*self.supercell_multiplier/angstrom_to_bohr
        b3=a3*self.supercell_multiplier/angstrom_to_bohr
……

in interpolate.py, i have added "dyn.ForcePositiveDefinite()" behind “dyn.Symmetrize()”

I have uploaded all the file to https://github.com/xinyu1905/sscha_ZrO2.git

**Comment by luigiranalli96** [comment]
Hi Xinyu, I have updated the last version of the interface, I would advice you to have a look at the C2 tutorial that I have created in order to familiarize with the workflow. It takes about 1Hr to complete it. 
If the problem if the interpolation is still there, let me know

**Comment by HsiaYan** [comment]
Hi, luigiranalli. I was wondering, what is this script "python_minimizer.py (in the 7(i))" and how do I get it? Thank you.

**Comment by luigiranalli96** [comment]
I have added the script rn!

Luigi

**Comment by HsiaYan** [comment]
Thank you for uploading the python file, however when I run it, it prompts me with the following error. It seems to be caused by a mismatch in the length of the array, have you encountered the following problem? I look forward to your reply, thanks.

[LOAD ENSEMBLE]: time elapsed for the cycle over the configurations: 40.558120012283325
[LOAD ENSEMBLE]: time elapsed to compute the current q vectors: 0.46511316299438477
[LOAD ENSEMBLE]: time elapsed while loading with numpy: 40.42270827293396
[LOAD ENSEMBLE]: time elapsed for computing sscha energy and forces: 0.04941201210021973
DYN CHANGED BY: 1.1102230246251565e-16
Time elapsed to prepare the rho update: 0.8185441493988037 s
 (of which to diagonalize and prepare the structure: 0.7259 s)
(of which to update sscha energies and forces: 0.0000 s)
(of which computing the Upsilon matrix: 0.0927 s)
(of which to update the weights): 0.2584877014160156 s
 | to copy the dynamical matrix: 0.0009675025939941406 s
 [GRADIENT] Time to prepare the gradient calculation: 0.09088969230651855 s
 [GRADIENT] Time to call the fortran code: 0.39269375801086426 s
 [GRADIENT] Time to get back in fourier space: 0.22621583938598633 s

 # ---------------- NEW MINIMIZATION STEP --------------------
Step ka =  1
 [GRADIENT] Time to prepare the gradient calculation: 0.07858943939208984 s
 [GRADIENT] Time to call the fortran code: 0.04730057716369629 s
 [GRADIENT] Time to get back in fourier space: 0.29562926292419434 s
Traceback (most recent call last):
  File "python_minimizer.py", line 46, in <module>
    minimizer.run(custom_function_post=IO.CFP_SaveAll)
  File "/public1/home/scb8066/.conda/envs/cell/lib/python3.8/site-packages/sscha/SchaMinimizer.py", line 1163, in run
    self.minimization_step(custom_function_gradient)
  File "/public1/home/scb8066/.conda/envs/cell/lib/python3.8/site-packages/sscha/SchaMinimizer.py", line 383, in minimization_step
    qe_sym.SymmetrizeFCQ(dyn_grad, np.array(self.dyn.q_stars), asr = "custom")
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

**Comment by ganbei233** [comment]
I spent a whole day debugging this same issue. The root cause is that the input POSCAR must be in Cartesian coordinates.

The documentation doesn't mention this explicitly, but the code assumes Cartesian format. Switching your coordinates from Direct to Cartesian should fix it immediately.
